# ============================================================
# extract_code.R
# Emit ONE self-contained R script that reproduces the model machinery: the
# Julia ODE registration, the compartmental R function, all the data the loss
# captured (bounds, matrices, masks, time grid), and the loss function itself.
#
#   extract_code(x, file = NULL, what = c("all", "model", "loss"))
#
#   x      a compartmentalFit or compartmentalModel.
#   file   if given, the script is written there (path returned invisibly);
#          otherwise the script is returned as a single character string.
#   what   "all" (default) -> the full merged, runnable script.
#          "model"         -> only the compartmental function (+ Julia reg).
#          "loss"          -> only the inlined data + loss function.
#
# RUN REQUIREMENT (irreducible): the loss solves the ODE through Julia, so the
# emitted script needs the package's Julia bridge available -- specifically the
# helpers registerJuliaODEFunction(), solveWithJulia() and denormalise(), and an
# initialised Julia session. Given those (i.e. the package loaded / setup.R
# sourced), the script runs end to end: it re-registers the ODE on the Julia
# side, then defines a callable loss over the inlined data. No prior fit needed.
# ============================================================

.xc_machinery <- function(x) {
  if (!inherits(x, "compartmentalFit") && !inherits(x, "compartmentalModel"))
    stop("extract_code() expects a compartmentalFit or compartmentalModel.")
  list(cf        = x$model$compartmental_function,
       julia     = x$model$julia_code,
       loss      = x$loss,
       env       = environment(x$loss),
       init_norm = x$bounds$init_norm)      # normalised start point for the fit
}

# Emit one R object as a re-parseable `name <- <code>` assignment.
#
#  * style = "readable" (default): deparse() with control = "all". This is
#    human-readable AND re-parseable, preserving names, dim/dimnames, NA, factor
#    levels, etc.; "all" includes "digits17", so doubles are written to 17
#    significant digits. That round-trips exactly for typical values, though R's
#    decimal parser is not always correctly-rounded, so the very last bit can
#    differ on adversarial doubles (e.g. pi reads back ~4e-16 off). Even an
#    "awkward" data matrix comes out as a readable structure(...) call.
#  * style = "fidelity": serialize(..., ascii = TRUE) embedded as a raw vector
#    and reconstructed with unserialize(). Opaque, but a guaranteed byte-exact
#    round-trip irrespective of object quirks -- use it when the last bit matters.
.xc_emit <- function(name, value, style = c("readable", "fidelity")) {
  style <- match.arg(style)
  if (style == "fidelity") {
    raw_ascii <- serialize(value, connection = NULL, ascii = TRUE)
    bytes <- paste(as.integer(raw_ascii), collapse = ",")
    return(paste0(name, " <- unserialize(as.raw(c(", bytes, ")))"))
  }
  src <- paste(deparse(value, control = "all"), collapse = "\n")
  paste0(name, " <- ", src)
}

# The objects the loss closure references but does not define (its captured
# build-time arguments). Kept in sync with lossFunction()'s formals.
.xc_loss_captured <- c(
  "lower_guesses", "upper_guesses",
  "matrix_data_points", "weight_matrix", "average_matrix",
  "obs_mask", "cens_mask", "limit_mat", "lcens_mask", "llimit_mat",
  "interval_mask", "ilow_mat", "iupp_mat", "idev_lo_mat", "idev_hi_mat",
  "asym_mask", "asym_val_mat", "asym_dev_mat", "asym_dir_mat",
  "time", "startpoint", "endpoint", "partition",
  "verbose",
  "checkpoint_file"
)

# ---- section builders ------------------------------------------------------

.xc_header <- function() paste0(
  "# =====================================================================\n",
  "# Self-contained compartmental model + loss (generated by extract_code).\n",
  "#\n",
  "# REQUIREMENT: compfit must be installed and Julia available -- the loss\n",
  "# solves the ODE via the compfit Julia bridge (solveWithJulia), so this is\n",
  "# not a pure-R script. The library(compfit) call below provides the bridge\n",
  "# helpers (registerJuliaODEFunction, solveWithJulia) and initialises Julia.\n",
  "#\n",
  "# Given that, this script is standalone: it re-registers the ODE on the Julia\n",
  "# side, defines the compartmental function, inlines all the data + helpers,\n",
  "# defines the loss, and FITS the model (L-BFGS-B) -- no prior fit required.\n",
  "#\n",
  "# Running the script performs the fit and prints the natural-scale estimates\n",
  "# (fitted_par). To only evaluate the loss at a point instead:\n",
  "#   best_state <- new.env(); best_state$error <- Inf; best_state$par <- NULL\n",
  "#   loss_function(par_normalised, best_state, show_error = FALSE)\n",
  "# where par_normalised is a [0,1] vector in the order of lower_guesses.\n",
  "# =====================================================================\n",
  "library(compfit)\n"
)

.xc_julia_section <- function(julia_code) {
  if (is.null(julia_code)) return(
    "# (No Julia ODE source stored on this object; ensure the ODE is registered.)\n")
  # deparse() on a character string yields a correctly-escaped, re-parseable R
  # string literal -- keeps the Julia source human-readable in the script.
  jc_literal <- paste(deparse(julia_code), collapse = "\n")
  paste0(
    "# ---- 1. Register the ODE function on the Julia side ----\n",
    "# Re-runs the same registration the model build performed, so solveWithJulia()\n",
    "# can find 'compartmental_function_jl'.\n",
    "julia_ode_code <- ", jc_literal, "\n",
    "registerJuliaODEFunction(julia_ode_code)\n"
  )
}

.xc_model_section <- function(cf) paste0(
  "# ---- 2. Compartmental model function (dX/dt), R side ----\n",
  "compartmental_function <- ", paste(deparse(cf), collapse = "\n"), "\n"
)

.xc_data_section <- function(env, style = "readable") {
  present <- .xc_loss_captured[vapply(.xc_loss_captured,
                function(nm) exists(nm, envir = env, inherits = FALSE), logical(1))]
  blocks <- vapply(present, function(nm) {
    if (nm == "checkpoint_file") {
      # Do NOT bake in the original path: make it location-independent and
      # side-effect-free. The checkpoint is only written when show_error = TRUE
      # AND a new best is found, so a tempfile keeps standalone evaluation clean.
      "checkpoint_file <- tempfile(fileext = \".rds\")"
    } else {
      .xc_emit(nm, get(nm, envir = env, inherits = FALSE), style = style)
    }
  }, character(1))
  paste0(
    "# ---- 3. Captured data the loss needs (inlined) ----\n",
    paste(blocks, collapse = "\n\n"), "\n"
  )
}

.xc_loss_section <- function(loss) paste0(
  "# ---- 4. Loss function ----\n",
  "# Generated parameter/state/error blocks are already inlined in the body.\n",
  "# Uses package helper solveWithJulia() (Julia bridge required).\n",
  "loss_function <- ", paste(deparse(loss), collapse = "\n"), "\n"
)

# normalise / denormalise inlined so the script does not depend on the package
# for them (only solveWithJulia + the Julia bridge remain external).
.xc_helpers_section <- function() paste0(
  "# ---- 0. Helpers (inlined; no package dependency) ----\n",
  "normalise <- ",   paste(deparse(normalise),   collapse = "\n"), "\n\n",
  "denormalise <- ", paste(deparse(denormalise), collapse = "\n"), "\n"
)

# A ready-to-run L-BFGS-B fit over the normalised [0,1] box, starting from the
# inlined init_norm, ending with denormalisation to natural-scale quantities.
.xc_fit_section <- function(init_norm, style = "readable") paste0(
  "# ---- 5. Fit: minimise the loss over the normalised [0,1] box ----\n",
  "# Mirrors the package's L-BFGS-B path. show_error = TRUE prints progress and\n",
  "# tracks the best solution in best_state. Swap in DEoptim / change control as\n",
  "# you like; the loss is just a function of a normalised [0,1] vector.\n",
  .xc_emit("init_norm", init_norm, style = style), "\n\n",
  "best_state <- new.env(); best_state$error <- Inf; best_state$par <- NULL\n\n",
  "fit_result <- optim(\n",
  "  par     = init_norm,\n",
  "  fn      = function(par) loss_function(par, best_state, show_error = TRUE),\n",
  "  method  = \"L-BFGS-B\",\n",
  "  lower   = 0, upper = 1,\n",
  "  control = list(maxit = 1000, factr = 1e7)\n",
  ")\n\n",
  "# Recover natural-scale parameters/states from the normalised optimum:\n",
  "fitted_par <- mapply(denormalise, fit_result$par, lower_guesses, upper_guesses)\n",
  "names(fitted_par) <- names(lower_guesses)\n",
  "print(fitted_par)\n"
)

# ---- main entry point ------------------------------------------------------
#' Export a fit as self-contained source code
#'
#' Emits portable R source that reproduces the model, loss, and/or fit from a
#' `"compartmentalFit"` (or model) object, inlining the captured data so the
#' script runs in a fresh session (given a Julia bridge).
#'
#' @param x A `"compartmentalFit"` or `"compartmentalModel"` object.
#' @param file Optional output path; if `NULL`, returns the code as a string.
#' @param what Which part(s) to emit: all, model, loss, or fit.
#' @param inline How captured data objects (bounds, data matrices, masks,
#'   `partition`, `init_norm`, ...) are written into the script. `"readable"`
#'   (default) emits them as human-readable, re-parseable `deparse()` code
#'   (names, dims, NAs preserved; doubles to 17 significant digits, which
#'   round-trips exactly for typical values but can differ by ~1 ULP on
#'   adversarial doubles, as R's decimal parser is not always correctly
#'   rounded). `"fidelity"` emits them as opaque `unserialize(as.raw(...))`
#'   blobs --- a guaranteed byte-exact round-trip, for when the last bit matters.
#' @return The generated code as a character string, invisibly (also written to
#'   `file` when supplied).
#' @examples
#' \dontrun{
#' extract_code(fit, file = file.path(tempdir(), "reproduce.R"), what = "all")
#' # opaque-but-byte-exact data blocks:
#' extract_code(fit, file = file.path(tempdir(), "exact.R"), inline = "fidelity")
#' }
#' @export
extract_code <- function(x, file = NULL, what = c("all", "model", "loss", "fit"),
                         inline = c("readable", "fidelity")) {
  what   <- match.arg(what)
  inline <- match.arg(inline)
  mac  <- .xc_machinery(x)

  parts <- .xc_header()
  # Helpers (normalise/denormalise) are needed by the loss and the fit; include
  # them whenever those are present.
  if (what %in% c("all", "loss", "fit"))
    parts <- c(parts, .xc_helpers_section())

  if (what %in% c("all", "model")) {
    if (is.null(mac$cf)) stop("No compartmental function found on this object.")
    parts <- c(parts, .xc_julia_section(mac$julia), .xc_model_section(mac$cf))
  }
  if (what %in% c("all", "loss", "fit")) {
    if (is.null(mac$loss)) stop("No loss function found on this object.")
    parts <- c(parts, .xc_data_section(mac$env, style = inline), .xc_loss_section(mac$loss))
  }
  if (what %in% c("all", "fit")) {
    if (is.null(mac$init_norm))
      stop("No init_norm (normalised start) available for the fit section.")
    parts <- c(parts, .xc_fit_section(mac$init_norm, style = inline))
  }

  code <- paste(parts, collapse = "\n\n")

  if (!is.null(file)) {
    writeLines(code, file)
    message("Wrote self-contained script (", sum(nchar(code)), " chars) to ", file)
    return(invisible(file))
  }
  code
}
